# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'dacabby'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Golf Mk1',  url: 'dacabby'}
- {name: 'Gallery', url: 'gallery'}
- {name: 'Posts',       url: 'posts'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'instagram', link:  'https://instagram.com/da_cabby'}

# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
