# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-133288884-2'

menu:
# - {name: 'cooking', url: 'cooking'}
- {name: 'cars',  url: 'cars'}
# - {name: 'it', url: 'it'}
- {name: 'gallery', url: 'gallery'}
# - {name: 'cloud', url: 'cloud'}
- {name: 'about', url: 'about'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
#- {icon: 'instagram', link:  'https://instagram.com/joshi.tsunami'}
- {icon: 'instagram', link:  'https://instagram.com/da_cabby'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Other posts...'

post_date_prefix: 'Written on'
